# Author: Kredwi
# Issues: https://github.com/kredwi/chathook/issues
debug: false # Enable debug mode (true - enabled, false - disabled).
async: true # Use asynchronous requests, if disabled, chat messages can be sent with a significant delay
timeout: 5000 # Timeout in milliseconds, after which the connection will be closed.
request_url: "http://localhost:8439" # The address of the server to which requests will be sent.
authorization: "" # Authorization token, if not needed, leave the field empty
config-version: 1 # Config version

# Message sector
message_sector:
 error_invalid_command: "§cThis command does not exist"
 config_is_reloaded: "§aConfiguration successfully reloaded"
 no_arguments: "§cNot enough arguments"
 no_permissions: "§cYou do not have enough permissions"

# List of player nicknames whose messages will not be sent to the server
disabled_players:
 - Kredwi
 - igor

# Other information that will be sent in the request
other_information:
 key_1: "%player_ip%"
 key_2: "%player_name%"